title:            don't global me bro
description:      I just wanna have some fun; Don't tell me what could be done
logo:             powerpuff_girl.png
disqus_shortname: dgmb
#Comment out url when working locally to resolve base urls correctly
#url:              http://whatever.com

# Owner/author information
owner:
  name:           Vikki
  avatar:         me_eyes_crop.jpg
  email:          vikki.read@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:    vikkiread
  facebook:
  github:     vikki
  linkedin:     vikki.read
  instagram:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    "http://plus.google.com/103415099856405998526"

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Articles
    url: /articles
  - title: Presentations
    url: http://vikki.github.io/presentations/
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title
